FROM python:3.13-slim

# Устанавливаем pg_dump и зависимости
RUN apt-get update && apt-get install -y \
    postgresql-client \
    && rm -rf /var/lib/apt/lists/*

# Python-зависимости
RUN pip install --no-cache-dir boto3

# Копируем скрипт планировщика
COPY app/backup/run_backup.sh /run_backup.sh
RUN chmod +x /run_backup.sh

CMD ["/run_backup.sh"]
